name: Rust

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
env:
    CARGO_TERM_COLOR: always
jobs:
    build-debug:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: true
          - name: Build
            run: cargo build --verbose
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: tunepulse-dev
                path: target/thumbv7em-none-eabihf/debug/tunepulse
                compression-level: 9
    build-release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: true
          - name: Build
            run: cargo build --release --verbose
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: tunepulse-release
                path: target/thumbv7em-none-eabihf/release/tunepulse
                compression-level: 9
